# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
