# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-09 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_choice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_user', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='user',
            field=models.ManyToManyField(blank=True, to='app.Person'),
        ),
    ]
